# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'waveLength.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import calculation



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(987, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.wavePeriod_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.wavePeriod_lineEdit.setObjectName("wavePeriod_lineEdit")
        self.verticalLayout.addWidget(self.wavePeriod_lineEdit)
        self.wave_Amplitude_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.wave_Amplitude_lineEdit.setObjectName("wave_Amplitude_lineEdit")
        self.verticalLayout.addWidget(self.wave_Amplitude_lineEdit)
        self.water_Depth_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.water_Depth_lineEdit.setObjectName("water_Depth_lineEdit")
        self.verticalLayout.addWidget(self.water_Depth_lineEdit)
        self.wave_Propagation_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.wave_Propagation_lineEdit.setObjectName("wave_Propagation_lineEdit")
        self.verticalLayout.addWidget(self.wave_Propagation_lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 2, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.coordinates_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.coordinates_lineEdit.setObjectName("coordinates_lineEdit")
        self.verticalLayout_4.addWidget(self.coordinates_lineEdit)
        self.vertical_coordinates_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.vertical_coordinates_lineEdit.setObjectName("vertical_coordinates_lineEdit")
        self.verticalLayout_4.addWidget(self.vertical_coordinates_lineEdit)
        self.time_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.time_lineEdit.setObjectName("time_lineEdit")
        self.verticalLayout_4.addWidget(self.time_lineEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 2, 0, 1, 3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_3)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_3.addWidget(self.graphicsView, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 246, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 3, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(611, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 4, 2, 1, 3)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 492, 372))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(413, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(413, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 2, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 1, 0, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 323, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 1, 2, 1, 1)
        self.Result_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Result_label.setObjectName("Result_label")
        self.gridLayout_2.addWidget(self.Result_label, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 2, 3, 2, 2)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.Logo_label = QtWidgets.QLabel(self.groupBox)
        self.Logo_label.setText("")
        self.Logo_label.setPixmap(QtGui.QPixmap("C:/Users/Aditi kumari/Downloads/Ashkam LOGO.png (1).png"))
        self.Logo_label.setObjectName("Logo_label")
        self.gridLayout_4.addWidget(self.Logo_label, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 411, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 2, 5, 2, 1)
        spacerItem7 = QtWidgets.QSpacerItem(93, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 4, 0, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(354, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 3, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 987, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Wave Period (T)"))
        self.label_3.setText(_translate("MainWindow", "Wave Amplitude (ζ)"))
        self.label_4.setText(_translate("MainWindow", "Water Depth (h)"))
        self.label_5.setText(_translate("MainWindow", "Wave Propagation (x)"))
        self.label_9.setText(_translate("MainWindow", "Coordinates (x, y)"))
        self.label_8.setText(_translate("MainWindow", "Vertical Coordinates (z)"))
        self.label_10.setText(_translate("MainWindow", "Time (t)"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.Result_label.setText(_translate("MainWindow", "RESULT"))
        self.label_6.setText(_translate("MainWindow", "INPUT"))
        self.label_12.setText(_translate("MainWindow", "© 2026 ASHKAM ENERGY Pvt. Ltd. | All Rights Reserved"))
        self.label.setText(_translate("MainWindow", "Sea Environment Wave Theory"))


        self.pushButton.clicked.connect(self.run_calculation)

    def run_calculation(self):

        try: 


            frontend = {
                "wave_period":float(self.wavePeriod_lineEdit.text()),
                "wave_amplitude":float(self.wave_Amplitude_lineEdit.text()),
                "water_depth":float(self.water_Depth_lineEdit.text()),
                "wave_propagation":float(self.wave_Propagation_lineEdit.text()),
                "coordinates":float(self.coordinates_lineEdit.text()),
                "vertical_coordinate":float(self.vertical_coordinates_lineEdit.text()),
                "time":float(self.time_lineEdit.text()),
            }

            print("Frontend data collected: ", frontend)
                
            # self.result = calculation(frontend)

            result = calculation.sea_environment_calculation(frontend)

            print("Calculation result:", result)

        except ValueError:
            QtWidgets.QMessageBox.warning(
                None,
                "Invalid Input",
                "Please enter valid numeric values in all input fields."
            )

         

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
