# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'waveLength.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import math
import io
import base64
import matplotlib.pyplot as plt
from datetime import datetime
from PyQt5.QtGui import QPixmap
from PyQt5.QtPrintSupport import QPrinter, QPrintDialog
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
import calculation
from utils import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setToolTip("")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        # self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        # self.label_5.setObjectName("label_5")
        # self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.wavePeriod_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.wavePeriod_lineEdit.setObjectName("wavePeriod_lineEdit")
        self.verticalLayout.addWidget(self.wavePeriod_lineEdit)
        self.wave_Amplitude_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.wave_Amplitude_lineEdit.setObjectName("wave_Amplitude_lineEdit")
        self.verticalLayout.addWidget(self.wave_Amplitude_lineEdit)
        self.water_Depth_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.water_Depth_lineEdit.setObjectName("water_Depth_lineEdit")
        self.verticalLayout.addWidget(self.water_Depth_lineEdit)
        # self.wave_Propagation_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        # self.wave_Propagation_lineEdit.setToolTipDuration(-1)
        # self.wave_Propagation_lineEdit.setObjectName("wave_Propagation_lineEdit")
        # self.verticalLayout.addWidget(self.wave_Propagation_lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 2, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.coordinates_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.coordinates_lineEdit.setObjectName("coordinates_lineEdit")
        self.verticalLayout_4.addWidget(self.coordinates_lineEdit)
        self.vertical_coordinates_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.vertical_coordinates_lineEdit.setObjectName("vertical_coordinates_lineEdit")
        self.verticalLayout_4.addWidget(self.vertical_coordinates_lineEdit)
        self.time_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.time_lineEdit.setObjectName("time_lineEdit")
        self.verticalLayout_4.addWidget(self.time_lineEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 2, 0, 1, 3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setSizePolicy(
            QtWidgets.QSizePolicy.Expanding,
            QtWidgets.QSizePolicy.Expanding
        )
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_3)
        self.graphicsView.setSizePolicy(
            QtWidgets.QSizePolicy.Expanding,
            QtWidgets.QSizePolicy.Expanding
        )
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_3.addWidget(self.graphicsView, 0, 0, 1, 1)
        
        self.gridLayout_4.addWidget(self.groupBox_3, 3, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(611, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 4, 2, 1, 4)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 478, 372))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(413, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(413, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 2, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 1, 0, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 323, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 1, 2, 1, 1)
        self.Result_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Result_label.setObjectName("Result_label")
        self.gridLayout_2.addWidget(self.Result_label, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 2, 3, 2, 3)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        font = QtGui.QFont()
        font.setBold(True)
        self.label_6.setFont(font)
        self.Result_label.setFont(font)
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)

        self.Logo_label = QtWidgets.QLabel(self.groupBox)
        self.Logo_label.setObjectName("Logo_label")
        self.Logo_label.setText("")

        pixmap = QtGui.QPixmap("assets/Ashkam LOGO.png (1).png")

        self.Logo_label.setPixmap(
            pixmap.scaled(
                180, 80,
                QtCore.Qt.KeepAspectRatio,
                QtCore.Qt.SmoothTransformation
            )
        )

        self.Logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo_label.setMinimumSize(180, 80)

        self.gridLayout_4.addWidget(
            self.Logo_label, 0, 0, 1, 1
        )
        spacerItem6 = QtWidgets.QSpacerItem(20, 411, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 2, 6, 2, 1)
        spacerItem7 = QtWidgets.QSpacerItem(93, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 4, 0, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(354, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 0, 4, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 987, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pdfButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pdfButton.setObjectName("pdfButton")
        self.pdfButton.setText("DOWNLOAD PDF")
        self.gridLayout.addWidget(self.pdfButton, 1, 1, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HYDRODYNAMIC LOADS"))
        self.label_2.setText(_translate("MainWindow", "Wave Period (T) (seconds)"))
        self.label_3.setText(_translate("MainWindow", "Wave Amplitude (ζ) (meters)"))
        self.label_4.setText(_translate("MainWindow", "Average Water Depth (h) (meters)"))
        # self.label_5.setText(_translate("MainWindow", "Direction of Wave Propagation (x)"))
        self.wavePeriod_lineEdit.setToolTip(_translate("MainWindow", "Enter the wave period (T) in seconds"))
        self.wave_Amplitude_lineEdit.setToolTip(_translate("MainWindow", "Enter the wave amplitude (ζ) in meters"))
        self.water_Depth_lineEdit.setToolTip(_translate("MainWindow", "Enter the average water depth (h) in meters"))
        # self.wave_Propagation_lineEdit.setToolTip(_translate("MainWindow", "What is the direction of wave propagation? (Enter \'x\' or \'y\')"))
        self.label_9.setText(_translate("MainWindow", "Coordinates of Wave Propagation (x)"))
        self.label_8.setText(_translate("MainWindow", "Vertical Coordinates (z)"))
        self.label_10.setText(_translate("MainWindow", "Time (t) (seconds)"))
        self.coordinates_lineEdit.setToolTip(_translate("MainWindow", "What is the coordinate as selected earlier? (Enter x or y)"))
        self.vertical_coordinates_lineEdit.setToolTip(_translate("MainWindow", "What is the vertical coordinate z (e.g., enter 5 for 5m depth)"))
        self.time_lineEdit.setToolTip(_translate("MainWindow", "What is the time? (Enter t)"))
        self.pushButton.setText(_translate("MainWindow", "Process"))
        self.pdfButton.setText(_translate("MainWindow", "DOWNLOAD PDF"))
        self.Result_label.setText(_translate("MainWindow", "RESULT"))
        self.label_6.setText(_translate("MainWindow", "INPUT"))
        self.label_12.setText(_translate("MainWindow", "© 2026 ASHKAM ENERGY Pvt. Ltd. | All Rights Reserved"))
        self.label.setText(_translate("MainWindow", "HYDRODYNAMIC LOADS"))

        self.pushButton.clicked.connect(self.run_calculation)
        self.pdfButton.clicked.connect(self.DOWNLOAD_pdf)
        self.pdfButton.setEnabled(False)

        
    
    def run_calculation(self):

        try: 


            frontend = {
                "wave_period":float(self.wavePeriod_lineEdit.text()),
                "wave_amplitude":float(self.wave_Amplitude_lineEdit.text()),
                "average_water_depth":float(self.water_Depth_lineEdit.text()),
                "coordinate_x_y":float(self.coordinates_lineEdit.text()),
                "vertical_coordinate_z":float(self.vertical_coordinates_lineEdit.text()),
                "time_t":float(self.time_lineEdit.text()),
            }

            print("Frontend data collected: ", frontend)
                
            # self.result = calculation(frontend)

            self.result = calculation.sea_environment_calculation(frontend)

            print("Calculation result:", self.result)


            self.displayHYDRODYNAMICsResults(self.result)

            self.show_dispersion_graph(
                self.result["waveNumber_infinite_k"],
                self.result["waveNumber_finite_k"],
                self.result["circular_frequency"],
                self.result["average_water_depth"],
                self.result["wave_period"]
            )
            self.pdfButton.setEnabled(True)


        except ValueError:
            QtWidgets.QMessageBox.warning(
                None,
                "Invalid Input",
                "Please enter valid numeric values in all input fields."
            )


    def displayHYDRODYNAMICsResults(self, result):
        self.textEdit.clear()
        now = datetime.now()
        
        try:
            html = f"""
            <html>
            <body>

            <div style="font-family: Arial; font-size: 10pt;">

                <h3 style="margin-bottom: 5px;">
                    HYDRODYNAMIC LOADS
                </h3>

                <p style="margin-top: 0px;">
                    <b>Result Updated:</b> {now}<br>
                    <b>Version:</b> 0.0.1
                </p>

                <h3 style="margin-top: 15px; margin-bottom: 8px;">
                    Wave Calculations for Deep Water and Finite Depth Water
                </h3>

                <table cellspacing="0" cellpadding="3">

                    <tr>
                        <td>Wave Period (T)</td>
                        <td>:</td>
                        <td>{result['wave_period']:.3f} seconds</td>
                    </tr>

                    <tr>
                        <td>Average Water Depth (h)</td>
                        <td>:</td>
                        <td>{result['average_water_depth']:.3f} meters</td>
                    </tr>

                    <tr>
                        <td>Circular Frequency (ω)</td>
                        <td>:</td>
                        <td>{result['circular_frequency']:.3f} rad/s</td>
                    </tr>

                    <tr>
                        <td>Wave Number (k)</td>
                        <td>:</td>
                        <td>{result['waveNumber_infinite_k']:.3f} m⁻¹</td>
                    </tr>

                    <tr>
                        <td>Wave Length (λ) - Deep Water</td>
                        <td>:</td>
                        <td>{result['wave_length_deep_water_lambda']:.3f} meters</td>
                    </tr>

                    <tr>
                        <td>Wave Number (k) - Finite Depth Water</td>
                        <td>:</td>
                        <td>{result['waveNumber_finite_k']:.3f} m⁻¹</td>
                    </tr>

                    <tr>
                        <td>Wave Length (λ) - Finite Depth Water</td>
                        <td>:</td>
                        <td>{result['wave_length_finite_depth_lambda']:.3f} meters</td>
                    </tr>

                </table>


                <h3 style="margin-top: 18px; margin-bottom: 8px;">
                    Velocity Potential and Wave Profile Calculations
                </h3>

                <table cellspacing="0" cellpadding="3">

                    <tr>
                        <td>Velocity Potential (φ) - Deep / Infinite Water</td>
                        <td>:</td>
                        <td>{result['velocity_Potential_phi_infiniteDepth']:.3f} m²/s</td>
                    </tr>

                    <tr>
                        <td>Velocity Potential (φ) - Finite Depth Water</td>
                        <td>:</td>
                        <td>{result['velocity_Potential_phi_finiteDepth']:.3f} m²/s</td>
                    </tr>

                    <tr>
                        <td>Wave Profile (ζ) - Finite Depth Water</td>
                        <td>:</td>
                        <td>{result['wave_Profile_finite_zeta']:.3f} meters</td>
                    </tr>

                    <tr>
                        <td>Wave Profile (ζ) - Deep / Infinite Water</td>
                        <td>:</td>
                        <td>{result['wave_Profile_infinite_zeta']:.3f} meters</td>
                    </tr>

                </table>


                <h3 style="margin-top: 18px; margin-bottom: 8px;">
                    Dynamic Pressure Calculations
                </h3>

                <table cellspacing="0" cellpadding="3">

                    <tr>
                        <td>Dynamic Pressure (p) - Deep / Infinite Water</td>
                        <td>:</td>
                        <td>{result['dynamic_pressure_infiniteDepth']:.3f} Pa</td>
                    </tr>

                    <tr>
                        <td>Dynamic Pressure (p) - Finite Depth Water</td>
                        <td>:</td>
                        <td>{result['dynamic_pressure_finiteDepth']:.3f} Pa</td>
                    </tr>

                </table>


                <h3 style="margin-top: 18px; margin-bottom: 8px;">
                    X Component of Velocity and Acceleration for Finite Depth Water
                </h3>

                <table cellspacing="0" cellpadding="3">

                    <tr>
                        <td>X Component of Velocity (u) - Finite Depth Water</td>
                        <td>:</td>
                        <td>{result['x_velocity_finiteDepth']:.3f} m/s</td>
                    </tr>

                    <tr>
                        <td>X Component of Acceleration (a) - Finite Depth Water</td>
                        <td>:</td>
                        <td>{result['x_acceleration_finiteDepth']:.3f} m/s²</td>
                    </tr>

                    <tr>
                        <td>X Component of Velocity (u) - Deep / Infinite Water</td>
                        <td>:</td>
                        <td>{result['x_velocity_infiniteDepth']:.3f} m/s</td>
                    </tr>

                    <tr>
                        <td>X Component of Acceleration (a) - Deep / Infinite Water</td>
                        <td>:</td>
                        <td>{result['x_acceleration_infiniteDepth']:.3f} m/s²</td>
                    </tr>

                </table>


                <h3 style="margin-top: 18px; margin-bottom: 8px;">
                    Z Component of Velocity and Acceleration for Finite Depth Water
                </h3>

                <table cellspacing="0" cellpadding="3">

                    <tr>
                        <td>Z Component of Velocity (u) - Finite Depth Water</td>
                        <td>:</td>
                        <td>{result['z_velocity_finiteDepth']:.3f} m/s</td>
                    </tr>

                    <tr>
                        <td>Z Component of Acceleration (a) - Finite Depth Water</td>
                        <td>:</td>
                        <td>{result['z_acceleration_finiteDepth']:.3f} m/s²</td>
                    </tr>

                    <tr>
                        <td>Z Component of Velocity (w) - Deep / Infinite Water</td>
                        <td>:</td>
                        <td>{result['z_velocity_infiniteDepth']:.3f} m/s</td>
                    </tr>

                    <tr>
                        <td>Z Component of Acceleration (a) - Deep / Infinite Water</td>
                        <td>:</td>
                        <td>{result['z_acceleration_infiniteDepth']:.3f} m/s²</td>
                    </tr>

                </table>

            </div>

            </body>
            </html>
            """

            self.textEdit.setHtml(html)


        except Exception as e:
            print("error",e)


    def get_graph_base64(self):
    # Create a temporary PNG from the current graph
        pixmap = self.graphicsView.grab()

        buffer = QtCore.QBuffer()
        buffer.open(QtCore.QIODevice.WriteOnly)
        pixmap.save(buffer, "PNG")

        image_data = bytes(buffer.data())
        buffer.close()

        return base64.b64encode(image_data).decode("utf-8")


    
# ___________________ Printing Dialog Code _________________________________

    def DOWNLOAD_pdf(self):

        
        try:
            file_path, _ = QtWidgets.QFileDialog.getSaveFileName(
                None,
                "Save PDF",
                "HYDRODYNAMIC_LOADS_Result.pdf",
                "PDF Files (*.pdf)"
            )

            graph_base64 = self.get_graph_base64()
            

            if not file_path:
                return

            # Make sure .pdf extension exists
            if not file_path.lower().endswith(".pdf"):
                file_path += ".pdf"

            # ---------------------------------------------------------
            # Create PDF printer
            # ---------------------------------------------------------
            printer = QPrinter(QPrinter.HighResolution)

            printer.setOutputFormat(QPrinter.PdfFormat)
            printer.setOutputFileName(file_path)

            # A4 page
            printer.setPaperSize(QPrinter.A4)

            # ---------------------------------------------------------
            # Create HTML document
            # ---------------------------------------------------------
            document = QtGui.QTextDocument()

            # ---------------------------------------------------------
            # Get input values
            # ---------------------------------------------------------
            wave_period = self.wavePeriod_lineEdit.text()
            wave_amplitude = self.wave_Amplitude_lineEdit.text()
            water_depth = self.water_Depth_lineEdit.text()
            coordinate = self.coordinates_lineEdit.text()
            vertical_coordinate = self.vertical_coordinates_lineEdit.text()
            time = self.time_lineEdit.text()

            # ---------------------------------------------------------
            # Get result section from QTextEdit
            # ---------------------------------------------------------
            result_html = self.textEdit.toHtml()

            # ---------------------------------------------------------
            # Create complete PDF HTML
            # ---------------------------------------------------------
            html = f"""
            <html>
            <head>
                <style>
                    body {{
                        font-family: Arial, sans-serif;
                        font-size: 10pt;
                    }}

                    .title {{
                        text-align: center;
                        font-size: 18pt;
                        font-weight: bold;
                    }}

                    .subtitle {{
                        text-align: center;
                        font-size: 11pt;
                    }}

                    .section {{
                        background-color: #16355d;
                        color: white;
                        padding: 6px;
                        font-size: 13pt;
                        font-weight: bold;
                        margin-top: 15px;
                    }}

                    table {{
                        width: 100%;
                        border-collapse: collapse;
                        margin-top: 8px;
                    }}

                    td {{
                        border: 1px solid #cccccc;
                        padding: 6px;
                    }}

                    .label {{
                        font-weight: bold;
                        width: 45%;
                    }}

                    .footer {{
                        text-align: center;
                        font-size: 8pt;
                        color: #666666;
                        margin-top: 20px;
                    }}

                
                    .header-title {{
                        width: 50%;
                        text-align: center;
                        font-size: 22pt;
                        font-weight: bold;
                    }}
                
            
                    .header-logo {{
                        text-align: left;
                        width:"20px";
                        height:"15px";
                    }}

                    .graph {{
                        width: 650px;
                        display: block;
                        margin: 0 auto;
                    }}
                </style>
            </head>


            <body>


                <img class="header-logo" src="assets/Ashkam LOGO.png (1).png">

                <div class="header-title" >HYDRODYNAMIC LOADS</div>

                <br>

                <div class="section">
                    INPUT
                </div>

                <table>
                    <tr>
                        <td class="label">Wave Period (T)</td>
                        <td>{wave_period} seconds</td>
                    </tr>

                    <tr>
                        <td class="label">Wave Amplitude (ζ)</td>
                        <td>{wave_amplitude} meters</td>
                    </tr>

                    <tr>
                        <td class="label">Average Water Depth (h)</td>
                        <td>{water_depth} meters</td>
                    </tr>

                    <tr>
                        <td class="label">Coordinates of Wave Propagation (x)</td>
                        <td>{coordinate}</td>
                    </tr>

                    <tr>
                        <td class="label">Vertical Coordinate (z)</td>
                        <td>{vertical_coordinate}</td>
                    </tr>

                    <tr>
                        <td class="label">Time (t)</td>
                        <td>{time} seconds</td>
                    </tr>
                </table>

                <div class="section">
                    RESULT
                </div>

                {result_html}

                <div class="section">
                    DISPERSION RELATION GRAPH
                </div>

                <div style="text-align: center;">
                    <img class="graph"
                        src="data:image/png;base64,{graph_base64}">
                </div>

                <br>

                <div class="footer">
                    © 2026 ASHKAM ENERGY Pvt. Ltd. | All Rights Reserved
                </div>

            </body>
            </html>
            """

            # ---------------------------------------------------------
            # Set HTML
            # ---------------------------------------------------------
            document.setHtml(html)

            # ---------------------------------------------------------
            # Print to PDF
            # ---------------------------------------------------------
            document.print_(printer)

            QtWidgets.QMessageBox.information(
                None,
                "PDF Generated",
                f"PDF saved successfully:\n\n{file_path}"
            )

        except Exception as e:
            QtWidgets.QMessageBox.critical(
                None,
                "PDF Error",
                f"Unable to generate PDF:\n\n{str(e)}"
            )


    def show_dispersion_graph(
                self,
                waveNumber_infinite_k,
                waveNumber_finite_k,
                circular_frequency,
                average_water_depth,
                wave_period
            ):

            # =========================================================
            # Generate k values
            # =========================================================

            max_k = max(
                2 * waveNumber_infinite_k,
                1.0
            )

            k_values = [
                i * (max_k / 200)
                for i in range(201)
            ]

            # =========================================================
            # Finite depth dispersion function
            # =========================================================

            finite_curve = [
                k * math.tanh(k * average_water_depth)
                for k in k_values
            ]

            # =========================================================
            # Target value
            # =========================================================

            target_value = (
                circular_frequency ** 2
            ) / g

            # =========================================================
            # Create figure based on GraphicsView size
            # =========================================================

            view_width = self.graphicsView.viewport().width()
            view_height = self.graphicsView.viewport().height()

            # Protect against very small values
            if view_width < 100:
                view_width = 800

            if view_height < 100:
                view_height = 500

            dpi = 100

            fig_width = view_width / dpi
            fig_height = view_height / dpi

            fig = plt.Figure(
                figsize=(fig_width, fig_height),
                dpi=dpi
            )

            ax = fig.add_subplot(111)

            # =========================================================
            # Plot finite-depth dispersion curve
            # =========================================================

            ax.plot(
                k_values,
                finite_curve,
                label=r'$k \tanh(kh)$',
                linewidth=2
            )

            # =========================================================
            # Target horizontal line
            # =========================================================

            ax.axhline(
                y=target_value,
                linestyle='--',
                label=r'$\omega^2/g$',
                linewidth=1.5
            )

            # =========================================================
            # Solved intersection
            # =========================================================

            ax.plot(
                waveNumber_finite_k,
                target_value,
                'go',
                markersize=8,
                label=f'Solved k = {waveNumber_finite_k:.4f} m⁻¹'
            )

            # =========================================================
            # Labels
            # =========================================================

            ax.set_title(
                f'Transcendental Dispersion Relation Solution\n'
                f'(T = {wave_period} seconds, h = {average_water_depth} meter)',
                fontsize=12
            )

            ax.set_xlabel(
                'Wave Number (k)',
                fontsize=10
            )

            ax.set_ylabel(
                'Value',
                fontsize=10
            )

            # =========================================================
            # Grid
            # =========================================================

            ax.grid(
                True,
                which='both',
                linestyle=':',
                alpha=0.6
            )

            # =========================================================
            # Legend
            # =========================================================

            ax.legend(
                loc='best',
                fontsize=9
            )

            # =========================================================
            # IMPORTANT: prevent clipping
            # =========================================================

            fig.subplots_adjust(
                left=0.10,
                right=0.97,
                top=0.88,
                bottom=0.12
            )

            # =========================================================
            # Convert Matplotlib figure to image
            # =========================================================

            canvas = FigureCanvas(fig)

            canvas.draw()

            width, height = canvas.get_width_height()

            image = QtGui.QImage(
                canvas.buffer_rgba(),
                width,
                height,
                QtGui.QImage.Format_RGBA8888
            ).copy()

            pixmap = QtGui.QPixmap.fromImage(image)

            # =========================================================
            # Create scene
            # =========================================================

            scene = QtWidgets.QGraphicsScene()

            scene.setSceneRect(
                0,
                0,
                pixmap.width(),
                pixmap.height()
            )

            scene.addPixmap(pixmap)

            self.graphicsView.setScene(scene)

            # =========================================================
            # Remove scrollbars
            # =========================================================

            self.graphicsView.setHorizontalScrollBarPolicy(
                QtCore.Qt.ScrollBarAlwaysOff
            )

            self.graphicsView.setVerticalScrollBarPolicy(
                QtCore.Qt.ScrollBarAlwaysOff
            )

            # =========================================================
            # Fit graph to available screen
            # =========================================================

            self.graphicsView.fitInView(
                scene.sceneRect(),
                QtCore.Qt.KeepAspectRatio
            )




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
